displayName=Doom Loot Value Fix
author=Draggin
description=Adjusts the Doom loot value to correctly value Sun-kissed bones at 0 GP instead of the incorrect 8,000 GP each
tags=doom,loot,value,bones,mokhaiotl
plugins=com.doomvalueadjustment.DoomValueAdjustmentPlugin
